import React, { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { PageHeader, Press, Screen, fonts, shadow, theme, typography, radius } from '../components/ui';

const groups=[
 {title:'Getting started',icon:'rocket-outline',items:[['How do I add my first property?','From Home, enter the property name when no property exists and tap Create property.'],['How do I add rooms and beds?','Open Rooms, add a room, then open that room to add its beds.'],['How do I add or switch to another property?','On Home, tap the property name at the top. Pick another property, or add a new one at the bottom of the list.'],['How do I rename a bed?','Open the room, tap the bed and change its label.']]},
 {title:'Tenants',icon:'people-outline',items:[['How do I add a tenant?','From Home tap Add tenant, choose an available bed and enter the tenant details.'],['How do I check out a tenant?','Open the tenant details and use the checkout action. The bed becomes vacant again.'],['Where do I see everyone who has stayed?','Open the Tenants tab. Switch between Staying now and Moved out.'],['How do I move a tenant to another bed?','Open the tenant and tap Move to another bed, then pick a vacant bed.'],['What is the difference between checking out and deleting a tenant?','Checking out keeps their record and rent history. Delete is for a record entered by mistake: it removes the tenant and all of their rent history.']]},
 {title:'Rent & payments',icon:'wallet-outline',items:[['Where can I see pending rent?','Home shows pending rent. Open Rent for the full list and payment actions.'],['How do I record rent?','Open Rent, choose the pending rent cycle and record the payment amount.'],['Where can I see a tenant\'s past payments?','Open the tenant. Rent history lists every month with each payment, its method and note.']]},
 {title:'Plans & free trial',icon:'pricetag-outline',items:[['How long is the free trial?','30 days. During the trial you can use 1 property, up to 150 beds and no co-owners, the same as Starter.'],['What do the plans include?','Starter: 1 property, 150 beds. Pro: up to 3 properties, 450 beds, 2 co-owners. Growth: up to 10 properties, 1,000 beds, 4 co-owners and priority support. Every plan has all the features.'],['What happens when the trial ends?','Your data stays safe, but you need a plan to keep using PG Manager.']]},
 {title:'Account & security',icon:'person-circle-outline',items:[['How do I change my password?','Open Account, then Password & devices.'],['How do I sign out another device?','Open Password & devices and remove the session you no longer recognise or use.'],['How do I give a partner or manager access?','Open Account, then Property settings, and fill in Add a co-owner. They sign in with that email and password and can manage the property, but cannot change its details or add co-owners. Co-owners are included in Pro (up to 2) and Growth (up to 4); the free trial and Starter include none.']]},
];
export default function HelpScreen({navigation}){return <Screen scroll><PageHeader eyebrow="Help centre" title="How can we help?" subtitle="Quick answers for managing your PG."/>{groups.map(g=><View key={g.title} style={styles.group}><View style={styles.head}><View style={styles.icon}><Ionicons name={g.icon} size={19} color={theme.brand}/></View><Text style={styles.groupTitle}>{g.title}</Text></View>{g.items.map(([q,a])=><Question key={q} q={q} a={a}/>)}</View>)}<Press scaleTo={0.985} accessibilityRole="button" onPress={()=>navigation.navigate('Support')} style={styles.support}><Ionicons name="chatbubble-ellipses-outline" size={20} color={theme.brand}/><View style={{flex:1}}><Text style={styles.q}>Still need help?</Text><Text style={styles.a}>Contact PG Manager support</Text></View><Ionicons name="chevron-forward" size={18} color={theme.textDisabled}/></Press></Screen>}
function Question({q,a}){const [open,setOpen]=useState(false);return <Press haptics="select" scaleTo={1} accessibilityRole="button" accessibilityState={{expanded:open}} onPress={()=>setOpen(v=>!v)} style={styles.question}><View style={styles.qrow}><Text style={styles.q}>{q}</Text><Ionicons name={open?'chevron-up':'chevron-down'} size={17} color={theme.muted}/></View>{open?<Text style={styles.a}>{a}</Text>:null}</Press>}
const styles=StyleSheet.create({title:{...typography.display,color:theme.text},sub:{...typography.body,color:theme.muted,marginTop:-8},group:{backgroundColor:theme.surface,borderRadius:radius.lg,borderWidth:StyleSheet.hairlineWidth,borderColor:theme.border,...shadow.card,overflow:'hidden'},head:{flexDirection:'row',alignItems:'center',gap:10,padding:16,backgroundColor:theme.brandWeak},icon:{width:34,height:34,borderRadius:17,alignItems:'center',justifyContent:'center',backgroundColor:theme.surface},groupTitle:{...typography.h3,color:theme.text},question:{padding:16,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:theme.border},qrow:{flexDirection:'row',gap:10,alignItems:'center'},q:{...typography.bodyStrong,color:theme.text,flex:1},a:{...typography.small,color:theme.muted,marginTop:8},support:{flexDirection:'row',alignItems:'center',gap:12,padding:16,backgroundColor:theme.surface,borderRadius:radius.lg,borderWidth:StyleSheet.hairlineWidth,borderColor:theme.border,...shadow.card}});