import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Screen, theme, typography, radius } from '../components/ui';

const groups=[
 {title:'Getting started',icon:'rocket-outline',items:[['How do I add my first property?','From Home, enter the property name when no property exists and tap Create property.'],['How do I add rooms and beds?','Open Rooms, add a room, then open that room to add its beds.']]},
 {title:'Tenants',icon:'people-outline',items:[['How do I add a tenant?','From Home tap Add tenant, choose an available bed and enter the tenant details.'],['How do I check out a tenant?','Open the tenant details and use the checkout action. The bed becomes vacant again.']]},
 {title:'Rent & payments',icon:'wallet-outline',items:[['Where can I see pending rent?','Home shows pending rent. Open Rent for the full list and payment actions.'],['How do I record rent?','Open Rent, choose the pending rent cycle and record the payment amount.']]},
 {title:'Account & security',icon:'person-circle-outline',items:[['How do I change my password?','Open Account, then Password & devices.'],['How do I sign out another device?','Open Password & devices and remove the session you no longer recognise or use.']]},
];
export default function HelpScreen({navigation}){return <Screen scroll><Text style={styles.title}>How can we help?</Text><Text style={styles.sub}>Quick answers for managing your PG.</Text>{groups.map(g=><View key={g.title} style={styles.group}><View style={styles.head}><View style={styles.icon}><Ionicons name={g.icon} size={19} color={theme.brand}/></View><Text style={styles.groupTitle}>{g.title}</Text></View>{g.items.map(([q,a])=><Question key={q} q={q} a={a}/>)}</View>)}<Pressable onPress={()=>navigation.navigate('Support')} style={styles.support}><Ionicons name="chatbubble-ellipses-outline" size={20} color={theme.brand}/><View style={{flex:1}}><Text style={styles.q}>Still need help?</Text><Text style={styles.a}>Contact PG Manager support</Text></View><Ionicons name="chevron-forward" size={18} color={theme.textDisabled}/></Pressable></Screen>}
function Question({q,a}){const [open,setOpen]=useState(false);return <Pressable onPress={()=>setOpen(v=>!v)} style={styles.question}><View style={styles.qrow}><Text style={styles.q}>{q}</Text><Ionicons name={open?'chevron-up':'chevron-down'} size={17} color={theme.muted}/></View>{open?<Text style={styles.a}>{a}</Text>:null}</Pressable>}
const styles=StyleSheet.create({title:{...typography.display,color:theme.text},sub:{...typography.body,color:theme.muted,marginTop:-8},group:{backgroundColor:theme.surface,borderRadius:radius.lg,borderWidth:1,borderColor:theme.border,overflow:'hidden'},head:{flexDirection:'row',alignItems:'center',gap:10,padding:16,backgroundColor:theme.brandWeak},icon:{width:34,height:34,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:theme.surface},groupTitle:{...typography.h3,color:theme.text},question:{padding:16,borderTopWidth:1,borderTopColor:theme.border},qrow:{flexDirection:'row',gap:10,alignItems:'center'},q:{...typography.body,color:theme.text,fontWeight:'600',flex:1},a:{...typography.small,color:theme.muted,marginTop:8},support:{flexDirection:'row',alignItems:'center',gap:12,padding:16,borderRadius:radius.lg,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border}});