import React,{useEffect,useState} from 'react';
import {StyleSheet,Text,View} from 'react-native';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button,Card,Field,PageHeader,QueryState,Row,Screen,SectionTitle,theme,typography} from '../components/ui';
import {useAuth} from '../context/AuthContext';import {useToast} from '../components/Toast';import {errorMessage} from '../lib/format';
export default function PropertySettingsScreen({route}){const {propertyId}=route.params;const {api}=useAuth();const toast=useToast();const qc=useQueryClient();const [form,setForm]=useState({name:'',address:'',city:''});const [email,setEmail]=useState('');const [busy,setBusy]=useState('');
const properties=useQuery({queryKey:['properties'],queryFn:async()=> (await api.get('/properties')).data.data});const members=useQuery({queryKey:['property-members',propertyId],queryFn:async()=> (await api.get(`/properties/${propertyId}/members`)).data.data});const property=(properties.data||[]).find(p=>p._id===propertyId);
useEffect(()=>{if(property)setForm({name:property.name||'',address:property.address||'',city:property.city||''})},[property?._id]);
async function save(){try{setBusy('save');await api.patch(`/properties/${propertyId}`,{name:form.name.trim(),address:form.address.trim(),city:form.city.trim()});await qc.invalidateQueries({queryKey:['properties']});qc.invalidateQueries({queryKey:['dashboard',propertyId]});toast.success('Property updated.')}catch(e){toast.error(errorMessage(e))}finally{setBusy('')}}
async function invite(){if(!email.trim())return;try{setBusy('invite');await api.post(`/properties/${propertyId}/members`,{email:email.trim()});setEmail('');members.refetch();toast.success('Co-owner invited.')}catch(e){toast.error(errorMessage(e))}finally{setBusy('')}}
return <Screen scroll><PageHeader title="Property settings" subtitle="Your property's details and who can manage it."/><QueryState query={properties}><SectionTitle>Details</SectionTitle><Field label="Property name" value={form.name} onChangeText={v=>setForm(p=>({...p,name:v}))} autoCapitalize="words"/><Field label="Address" value={form.address} onChangeText={v=>setForm(p=>({...p,address:v}))} autoCapitalize="words"/><Field label="City" value={form.city} onChangeText={v=>setForm(p=>({...p,city:v}))} autoCapitalize="words"/><Button onPress={save} loading={busy==='save'}>Save property</Button></QueryState><SectionTitle>Owners & access</SectionTitle><QueryState query={members}>{(members.data||[]).map(m=><Row key={m._id} icon="person-outline" title={m.name||m.email||'Member'} subtitle={m.email} badge={m.role}/>)}</QueryState><Card style={s.invite}><Field label="Co-owner email" value={email} onChangeText={setEmail} keyboardType="email-address" placeholder="name@example.com"/><Button variant="ghost" onPress={invite} loading={busy==='invite'}>Invite co-owner</Button></Card></Screen>}
const s=StyleSheet.create({title:{...typography.h1,color:theme.text},invite:{gap:12}});