import React, { useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Button, PageHeader, PasswordField, QueryState, Screen, SectionTitle, shadow, theme, typography, radius } from '../components/ui';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../components/Toast';
import { errorMessage } from '../lib/format';

export default function SecurityScreen(){const {api,clearSession}=useAuth();const toast=useToast();const [form,setForm]=useState({currentPassword:'',newPassword:''});const sessions=useQuery({queryKey:['auth-sessions'],queryFn:async()=> (await api.get('/auth/sessions')).data.data});const change=useMutation({mutationFn:()=>api.post('/auth/change-password',form),onSuccess:async(res)=>{setForm({currentPassword:'',newPassword:''});toast.success('Password changed. Other devices were signed out.');await sessions.refetch();},onError:e=>toast.error(errorMessage(e))});const revoke=async id=>{try{await api.delete(`/auth/sessions/${id}`);toast.success('Device signed out.');sessions.refetch();}catch(e){toast.error(errorMessage(e))}};const all=()=>Alert.alert('Sign out everywhere?','Every device, including this one, will need to sign in again.',[{text:'Cancel',style:'cancel'},{text:'Sign out everywhere',style:'destructive',onPress:async()=>{try{await api.post('/auth/logout-all');await clearSession();}catch(e){toast.error(errorMessage(e))}}}]);return <Screen scroll><PageHeader title="Password & devices" subtitle="Change your password and see where you're signed in."/><SectionTitle>Change your password</SectionTitle><PasswordField label="Current password" value={form.currentPassword} onChangeText={v=>setForm(p=>({...p,currentPassword:v}))}/><PasswordField label="New password" value={form.newPassword} onChangeText={v=>setForm(p=>({...p,newPassword:v}))}/><Button loading={change.isPending} onPress={()=>change.mutate()}>Change password</Button><SectionTitle>Signed in on</SectionTitle><QueryState query={sessions}>{(sessions.data||[]).map(s=><View key={s.id} style={styles.session}><View style={styles.deviceIcon}><Ionicons name={s.current?'phone-portrait':'phone-portrait-outline'} size={19} color={theme.primary}/></View><View style={{flex:1}}><Text style={styles.device}>{s.current?'This device':'Signed-in device'}</Text><Text style={styles.meta}>{[s.ip,s.lastUsedAt&&new Date(s.lastUsedAt).toLocaleDateString()].filter(Boolean).join(' · ')}</Text></View>{s.current?null:<Button size="sm" variant="danger" onPress={()=>revoke(s.id)}>Remove</Button>}</View>)}</QueryState><Button variant="danger" onPress={all}>Sign out everywhere</Button></Screen>}
const styles=StyleSheet.create({title:{...typography.h1,color:theme.text},heading:{...typography.h3,color:theme.text,marginTop:12},session:{flexDirection:'row',alignItems:'center',gap:12,padding:16,backgroundColor:theme.surface,borderRadius:radius.lg,borderWidth:StyleSheet.hairlineWidth,borderColor:theme.border,...shadow.card},deviceIcon:{width:40,height:40,borderRadius:20,backgroundColor:theme.primarySubtle,alignItems:'center',justifyContent:'center'},device:{...typography.bodyStrong,color:theme.text},meta:{...typography.caption,color:theme.muted,marginTop:3}});