import React, { useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Button, Field, FormSection, PasswordField, QueryState, Screen, theme, typography, radius } from '../components/ui';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../components/Toast';
import { errorMessage } from '../lib/format';

export default function SecurityScreen(){const {api,clearSession}=useAuth();const toast=useToast();const [form,setForm]=useState({currentPassword:'',newPassword:''});const sessions=useQuery({queryKey:['auth-sessions'],queryFn:async()=> (await api.get('/auth/sessions')).data.data});const change=useMutation({mutationFn:()=>api.post('/auth/change-password',form),onSuccess:async(res)=>{setForm({currentPassword:'',newPassword:''});toast.success('Password changed. Other devices were signed out.');await sessions.refetch();},onError:e=>toast.error(errorMessage(e))});const revoke=async id=>{try{await api.delete(`/auth/sessions/${id}`);toast.success('Device signed out.');sessions.refetch();}catch(e){toast.error(errorMessage(e))}};const all=()=>Alert.alert('Sign out everywhere?','Every device, including this one, will need to sign in again.',[{text:'Cancel',style:'cancel'},{text:'Sign out everywhere',style:'destructive',onPress:async()=>{try{await api.post('/auth/logout-all');await clearSession();}catch(e){toast.error(errorMessage(e))}}}]);return <Screen scroll><Text style={styles.title}>Password & devices</Text><FormSection title="Change password"><PasswordField label="Current password" value={form.currentPassword} onChangeText={v=>setForm(p=>({...p,currentPassword:v}))}/><PasswordField label="New password" value={form.newPassword} onChangeText={v=>setForm(p=>({...p,newPassword:v}))}/><Button loading={change.isPending} onPress={()=>change.mutate()}>Change password</Button></FormSection><Text style={styles.heading}>Signed in on</Text><QueryState query={sessions}>{(sessions.data||[]).map(s=><View key={s.id} style={styles.session}><View style={{flex:1}}><Text style={styles.device}>{s.current?'This device':'Signed-in device'}</Text><Text style={styles.meta}>{[s.ip,s.lastUsedAt&&new Date(s.lastUsedAt).toLocaleDateString()].filter(Boolean).join(' · ')}</Text></View>{s.current?null:<Button variant="tertiary" onPress={()=>revoke(s.id)}>Remove</Button>}</View>)}</QueryState><Button variant="danger" onPress={all}>Sign out everywhere</Button></Screen>}
const styles=StyleSheet.create({title:{...typography.h1,color:theme.text},heading:{...typography.h3,color:theme.text,marginTop:12},session:{flexDirection:'row',alignItems:'center',gap:12,padding:16,borderRadius:radius.lg,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border},device:{...typography.body,color:theme.text,fontWeight:'600'},meta:{...typography.caption,color:theme.muted,marginTop:3}});